*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZMMGF_HPSM_INTERGRATIONU01.
                    "ZBAPI_WERKSCODE_GETLIST
INCLUDE LZMMGF_HPSM_INTERGRATIONU02.
                    "ZBAPI_LGORTCODE_GETLIST
