FUNCTION-POOL ZMMGF_HPSM_INTERGRATION.      "MESSAGE-ID ..

* INCLUDE LZMMGF_HPSM_INTERGRATIOND...       " Local class definition

TABLES: T001W,
        T001K.

TYPES: BEGIN OF E_T001KW,
        BWKEY TYPE BWKEY,
        BUKRS TYPE BUKRS,
        WERKS TYPE WERKS_D,
       END OF E_T001KW.

DATA: LM_WERKSCODE_LIST TYPE TABLE OF ZMMGF_HPSM_INTERGRATION_001 WITH HEADER LINE,
      LM_LGORTCODE_LIST TYPE TABLE OF ZMMGF_HPSM_INTERGRATION_002 WITH HEADER LINE,
      IT_T001KW TYPE TABLE OF E_T001KW WITH HEADER LINE.

DATA: BEGIN OF MESSAGE,
        MSGTY LIKE SY-MSGTY,
        MSGID LIKE SY-MSGID,
        MSGNO LIKE SY-MSGNO,
        MSGV1 LIKE SY-MSGV1,
        MSGV2 LIKE SY-MSGV2,
        MSGV3 LIKE SY-MSGV3,
        MSGV4 LIKE SY-MSGV4,
     END OF MESSAGE.
